status = [
    "build (nightly, ubuntu-latest)",
    "build (nightly, windows-latest)",
    "build (stable, macos-latest)",
    "build (stable, ubuntu-latest)",
    "build (stable, windows-latest)",
    "ci",
]

use_squash_merge = true
